{% set name = "NTPoly" %}
{% set version = "2.7.1" %}
{% set build = 0 %}
{% set mpi = mpi or "mpich" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/william-dawson/{{ name }}/archive/refs/tags/{{ name|lower }}-v{{ version }}.tar.gz
  sha256: c15d9f51ac054b4ef0565ce5c4c8589c10bdbab4dc3442ebd109691e2bbfc7e2

build:
  number: {{ build }}
  skip: true  # [win]
  script:
    - export CXX="$PREFIX/bin/mpicxx" CC="$PREFIX/bin/mpicc" FC="$PREFIX/bin/mpifort"
    - cmake ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=ON -G Ninja -B _build
    - cmake --build _build
    - cmake --install _build

  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ name|lower }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - {{ mpi }}
    - libblas
    - liblapack
  run:
    - {{ mpi }}


test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}
    - test -f $PREFIX/lib/lib{{ name }}CPP${SHLIB_EXT}
    - test -f $PREFIX/lib/lib{{ name }}Wrapper${SHLIB_EXT}

about:
  home: https://william-dawson.github.io/NTPoly/
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: A massively parallel library for computing the functions of sparse matrices.
  doc_url: https://william-dawson.github.io/NTPoly/documentation/
  dev_url: https://github.com/william-dawson/NTPoly/tree/ntpoly-v2.7.0

extra:
  recipe-maintainers:
    - william-dawson
    - awvwgk
