{% set name = "NTPoly" %}
{% set version = "3.1.1" %}
{% set build = 0 %}
{% set mpi = mpi or "mpich" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/william-dawson/{{ name }}/archive/refs/tags/{{ name|lower }}-v{{ version }}.tar.gz
  sha256: 1a7cadba2f8c9de7aebecfd7997848f1f5f0f8526100446a5ef7bd0997b8ea66

build:
  number: {{ build }}
  skip: true  # [win]
  script:
    - export OPAL_PREFIX=$PREFIX  # [mpi == "openmpi"]
    - export CXX="mpicxx" CC="mpicc" FC="mpifort"
    - cmake ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=ON -G Ninja -B _build
    - cmake --build _build
    - cmake --install _build

  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ pin_subpackage('ntpoly', max_pin='x.x') }} {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ mpi }}  # [mpi == "openmpi" and build_platform != target_platform]
  host:
    - {{ mpi }}
    - libblas
    - liblapack
  run:
    - {{ mpi }}


test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}
    - test -f $PREFIX/lib/lib{{ name }}CPP${SHLIB_EXT}
    - test -f $PREFIX/lib/lib{{ name }}Wrapper${SHLIB_EXT}

about:
  home: https://william-dawson.github.io/NTPoly/
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: A massively parallel library for computing the functions of sparse matrices.
  doc_url: https://william-dawson.github.io/NTPoly/documentation/
  dev_url: https://github.com/william-dawson/NTPoly/tree/ntpoly-v2.7.0

extra:
  recipe-maintainers:
    - william-dawson
    - awvwgk
